export const COSMETIC_CATEGORIES = [
  { value: "bodycare", label: "Chăm sóc cơ thể" },
  { value: "bodylotion", label: "Kem dưỡng thể" },
  { value: "bodymist", label: "Xịt thơm toàn thân" },
  { value: "bodywash", label: "Sữa tắm" },
  { value: "exfoliation", label: "Tẩy tế bào chết" },
  { value: "giftsets", label: "Bộ quà tặng" },
  { value: "eyecare", label: "Chăm sóc mắt" },
  { value: "haircare", label: "Chăm sóc tóc" },
  { value: "lipcare", label: "Chăm sóc môi" },
  { value: "nailcare", label: "Chăm sóc móng" },
  { value: "cuticlecare", label: "Chăm sóc da xung quanh móng" },
  { value: "eyebrow", label: "Chăm sóc lông mày" },
  { value: "footcare", label: "Chăm sóc chân" },
  { value: "antiaging", label: "Chống lão hóa" },
  { value: "brushes", label: "Cọ trang điểm" },
  { value: "contour", label: "Contouring" },
  { value: "cologne", label: "Cologne" },
  { value: "hairoil", label: "Dầu dưỡng tóc" },
  { value: "shampoo", label: "Dầu gội" },
  { value: "conditioner", label: "Dầu xả" },
  { value: "moisturizing", label: "Dưỡng ẩm" },
  { value: "tools", label: "Dụng cụ làm đẹp" },
  { value: "mirrors", label: "Gương trang điểm" },
  { value: "highlighter", label: "Highlighter" },
  { value: "japanese", label: "J-Beauty" },
  { value: "korean", label: "K-Beauty" },
  { value: "foundation", label: "Kem nền" },
  { value: "concealer", label: "Kem che khuyết điểm" },
  { value: "suncare", label: "Kem chống nắng" },
  { value: "handcream", label: "Kem dưỡng tay" },
  { value: "hairspray", label: "Keo xịt tóc" },
  { value: "eyeliner", label: "Kẻ mắt" },
  { value: "lipliner", label: "Chì kẻ môi" },
  { value: "cleansing", label: "Làm sạch" },
  { value: "whitening", label: "Làm trắng da" },
  { value: "deodorant", label: "Lăn khử mùi" },
  { value: "mask", label: "Mặt nạ" },
  { value: "hairmask", label: "Mặt nạ tóc" },
  { value: "organic", label: "Mỹ phẩm organic" },
  { value: "french", label: "Mỹ phẩm Pháp" },
  { value: "mencare", label: "Mỹ phẩm nam" },
  { value: "teenskin", label: "Mỹ phẩm tuổi teen" },
  { value: "sponges", label: "Mút trang điểm" },
  { value: "fragrance", label: "Nước hoa" },
  { value: "perfume", label: "Nước hoa" },
  { value: "toner", label: "Toner/Nước hoa hồng" },
  { value: "tweezers", label: "Nhíp" },
  { value: "blush", label: "Phấn má hồng" },
  { value: "eyeshadow", label: "Phấn mắt" },
  { value: "powder", label: "Phấn phủ" },
  { value: "premiumluxury", label: "Cao cấp/Luxury" },
  { value: "serum", label: "Serum" },
  { value: "lipstick", label: "Son môi" },
  { value: "lipgloss", label: "Son bóng" },
  { value: "nailpolish", label: "Sơn móng tay" },
  { value: "nailremover", label: "Tẩy sơn móng" },
  { value: "makeup", label: "Trang điểm" },
  { value: "antiacne", label: "Trị mụn" },
  { value: "sensitiverskin", label: "Da nhạy cảm" },
  { value: "mascara", label: "Mascara" },
] as const;

export const STOCK_FILTERS = [
  { value: "all", label: "Tất cả" },
  { value: "in-stock", label: "Còn hàng" },
  { value: "low-stock", label: "Sắp hết" },
  { value: "out-of-stock", label: "Hết hàng" },
] as const;

export const PAGE_SIZE_OPTIONS = [10, 20, 50] as const;